trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'SonarQubeConnection'
        scannerMode: 'Other'
    - task: Maven@3
      displayName: 'Build'
      inputs:
        goals: 'clean install sonar:sonar'
        mavenOptions: '-DskipTests -Dsonar.host.url=http://18.208.148.153:9000 -Dsonar.login=admin -Dsonar.password=Default@123456 -Dsonar.java.binaries=target/test-classes/com/talentx/account/controllerTest/'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(System.DefaultWorkingDirectory)
 
    - task: PublishBuildArtifacts@1
      displayName: 'Archive Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'talentx'
        publishLocation: 'Container'

- stage: UnitTest
  jobs:
  - job: UnitTest
    steps:
    - task: Maven@3
      displayName: 'Unit Test'
      inputs:
        goals: 'test'
        mavenOptions: '-Xmx3072m'

- stage: CheckstyleAnalysis
  jobs:
  - job: CheckstyleAnalysis
    steps:
    - task: Maven@3
      displayName: 'Checkstyle Analysis'
      inputs:
        goals: 'checkstyle:checkstyle'
        mavenOptions: '-Xmx3072m'