# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Prod
    jobs:
      - deployment: Helm_Deployment_Prod
        environment: prod
        variables:
          env: prod
        strategy:
         runOnce: 
          deploy:
            steps:
              - checkout: self
                clean: true
                submodules: true | recursive
                path: helm
                displayName: Checkout
              - task: Bash@3
                displayName: 'Helm dependency update'
                inputs:
                  targetType: 'inline'
                  script: |
                    ls
                    helm dependency list talentxcharts
                    helm dependency list talentxcharts
              - task: HelmDeploy@0
                displayName: 'Login'
                inputs:
                  connectionType: 'Kubernetes Service Connection'
                  kubernetesServiceConnection: 'kubeTalentxConnect'
                  command: 'login'
              - task: Bash@3
                displayName: 'Helm Uppgrade'
                inputs:
                  targetType: 'inline'
                  script: |
                    helm upgrade --install --force talentxstack $(Agent.BuildDirectory)/helm/talentxcharts



