trigger:
- talentx-CICD

pool:
  vmImage: 'ubuntu-latest'

variables:
  registry: "securewolf/talentx_app"
  registryCredential: 'talentxDHub'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Maven@3
      displayName: 'Build'
      inputs:
        goals: 'clean install -DskipTests'
        #options: '-Xmx3072m'

    - task: PublishBuildArtifacts@1
      displayName: 'Archive Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'talentx'
        publishLocation: 'Container'

- stage: UnitTest
  dependsOn: Build
  jobs:
  - job: UnitTest
    steps:
    - task: Maven@3
      displayName: 'Unit Test'
      inputs:
        goals: 'test'
        #options: '-Xmx3072m'

- stage: CheckstyleAnalysis
  dependsOn: UnitTest
  jobs:
  - job: CheckstyleAnalysis
    steps:
    - task: Maven@3
      displayName: 'Checkstyle Analysis'
      inputs:
        goals: 'checkstyle:checkstyle'
        #options: '-Xmx3072m'

- stage: CodeAnalysisWithSonarQube 
  dependsOn: CheckstyleAnalysis
  jobs:
  - job: CodeAnalysis
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'SonarQubeConnection'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'talentx'
        cliProjectName: 'talentx'
        cliSources: 'src/'
        cliTests: 'target/surefire-reports/'
        cliBinaries: 'target/test-classes/com/talentx/account/controllerTest/'
        cliJavaCheckstyleReportPaths: 'target/checkstyle-result.xml'
    
    - task: SonarQubeAnalyze@4
    
    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'

- stage: BuildTalentxAppImage
  dependsOn: CodeAnalysisWithSonarqube 
  jobs:
  - job: BuildImage
    steps:
    - task: Docker@2
      displayName: 'Build Talentx App Image'
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'
        
- stage: UploadImageToDockerhub
  dependsOn: BuildTalentxAppImage
  jobs:
  - job: UploadImage
    steps:
    - task: Docker@2
      displayName: 'Upload Image to Dockerhub'
      inputs:
        command: 'push'
        repository: '$(registry)'
        tags: 'latest'

- stage: RemoveOldAppImage
  dependsOn: UploadImageToDockerhub
  jobs:
  - job: RemoveImage
    steps:
    - task: PowerShell@2
      displayName: 'Remove Old App Image'
      inputs:
        targetType: 'inline'
        script: 'docker rmi $(registry):$(Build.BuildId)'

- stage: AppDeploymentOnK8s
  dependsOn: RemoveOldAppImage
  jobs:
  - deployment: DeployApp
    displayName: 'App Deployment on K8s'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'
              
          - task: HelmDeploy@0
            inputs:
              command: 'upgrade'
              chartType: 'Name'
              chartName: 'talentx-stack'
              releaseName: 'talentx-release'
              overrideValues: '--set appimage=$(registry):$(Build.BuildId)'
              namespace: 'prod'

